---
name: Test Upload Python Package to Test PyPI

"on":
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: testing
    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write
    env:
      SETUPTOOLS_SCM_OVERRIDES_FOR_CO2MINI: "{local_scheme = \"no-local-version\"}"
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Set up Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version-file: "pyproject.toml"
      - name: Install uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0
        with:
          activate-environment: "true"
          enable-cache: "false"
      - name: Install dependencies
        run: |
          uv sync --all-extras --dev
      - name: Build
        run: python -m build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          repository-url: https://test.pypi.org/legacy/
          verbose: true
